"""
Utility functions for the FastAPI application.
"""
# These will be imported when needed via direct imports
# from apps.fastapi.src.utils.cost_nutrition_filters import ...
# from apps.fastapi.src.utils.sql_builders import ...
# from apps.fastapi.src.utils.currency_detector import ...
